apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-16T10:59:20Z
  generation: 1
  labels:
    run: madrid
  name: madrid
  namespace: default
  resourceVersion: "3497"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/madrid
  uid: 8d4045ef-47da-11e9-a70e-42010a840159
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: madrid
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: madrid
    spec:
      containers:
      - image: gcr.io/kubernetes-course-luislard/github.com/luislard/googlecloud-workshop:570f10fceb0f7db610b0ba632664fd139e7d7163
        imagePullPolicy: IfNotPresent
        name: madrid
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
